apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: myfleet-rg
  namespace: clusters
  annotations:
    serviceoperator.azure.com/reconcile-policy: "skip"
spec:
  location: eastus2