apiVersion: v1
kind: Namespace
metadata:
  name: azureserviceoperator-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: aso2
  namespace: cluster-config
spec:
  interval: 24h
  url: https://raw.githubusercontent.com/Azure/azure-service-operator/main/v2/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aso2
  namespace: cluster-config
spec:
  interval: 30m
  targetNamespace: azureserviceoperator-system
  chart:
    spec:
      chart: azure-service-operator
      version: "2.x"
      sourceRef:
        kind: HelmRepository
        name: aso2
        namespace: cluster-config
      interval: 12h
  values:
    azureSubscriptionID: ${SUBID}
    azureTenantID: ${TENANT} 
    azureClientID: ${IDENTITY}
    useWorkloadIdentityAuth: true
    crdPattern: 'resources.azure.com/*;containerservice.azure.com/*;kubernetesconfiguration.azure.com/*'
  dependsOn:
    - name: cert-manager